Update (as other 2 intel test scripts) in case we want to add additional  experiments from verification_other.

diff --git a/run_tests/engaging/test_engag_op64_adm b/run_tests/engaging/test_engag_op64_adm
--- a/run_tests/engaging/test_engag_op64_adm
+++ b/run_tests/engaging/test_engag_op64_adm
@@ -9,7 +9,7 @@
 #SBATCH -o /home/jm_c/test_engaging/output/o64Adm_tst.stdout
 #SBATCH --no-requeue --constraint=centos6
 
-# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/engaging/test_engag_op64_adm,v 1.13 2018/04/03 00:27:08 jmc Exp $
+# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/engaging/test_engag_op64_adm,v 1.14 2018/11/07 23:14:37 jmc Exp $
 # $Name:  $
 
 if test -f /etc/profile.d/modules.sh ; then
@@ -31,7 +31,7 @@ TST_DIR="/pool001/jm_c/test_$dNam"
 tmpFil="/tmp/"`basename $0`".$$"
   cmdCVS='cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack -q'
 #- which GitHub repository to use and how to access it:
-  git_repo='MITgcm';  git_code='MITgcm'
+  git_repo='MITgcm';  git_code='MITgcm' ; git_other='verification_other'
  #git_repo='altMITgcm'; #git_code='MITgcm66h'
 #--
   git_repo="https://github.com/$git_repo"
@@ -104,7 +104,18 @@ if [ $dsp -gt 99 ] ; then
   exit
 fi
 if [ $checkOut -eq 1 ] ; then
-  if test -e $gcmDIR/.git/config ; then
+  if test ! -e $gcmDIR/.git/config ; then
+    echo "no file: $gcmDIR/.git/config => try to download a fresh clone"
+    checkOut=2
+  fi
+  if test "x$addExp" != x ; then
+    if test ! -e $gcmDIR/$git_other/.git/config ; then
+      echo "no file: $gcmDIR/$git_other/.git/config => try a fresh clone"
+      checkOut=2
+    fi
+  fi
+fi
+if [ $checkOut -eq 1 ] ; then
     echo "cleaning output from $gcmDIR/verification :"
 #- remove previous output tar files and tar & remove previous output-dir
     /bin/rm -f $gcmDIR/verification/??_${dNam}-${sfx}_????????_?.tar.gz
@@ -123,6 +134,13 @@ if [ $checkOut -eq 1 ] ; then
       done )
 #   ( cd $gcmDIR/verification ; ../tools/do_tst_2+2 -clean )
     ( cd $gcmDIR/verification ; ./testreport $typ -clean )
+  if test "x$addExp" != x ; then
+    ( cd $gcmDIR/verification
+      listD=`ls -o | grep '^l' | awk '{print $8}' 2> /dev/null`
+      echo " + remove local links: $listD"
+      /bin/rm -f $listD
+    )
+  fi
     echo "Update MITgcm code in dir $gcmDIR :"
     ( cd $gcmDIR ; git pull ) 2>&1
     retVal=$?
@@ -132,9 +150,16 @@ if [ $checkOut -eq 1 ] ; then
     fi
     echo "  and checkout master:"
     ( cd $gcmDIR ; git checkout master -- . ) 2>&1
-  else
-    echo "no file: $gcmDIR/.git/config => try to download a fresh clone"
-    checkOut=2
+  if test "x$addExp" != x ; then
+    echo "Update $git_other code in dir $gcmDIR/$git_other :"
+    ( cd $gcmDIR/$git_other ; git pull ) 2>&1
+    retVal=$?
+    if test "x$retVal" != x0 ; then
+       echo "git pull on '"`hostname`"' fail (return val=$retVal) => exit"
+       exit
+    fi
+    echo "  and checkout master:"
+    ( cd $gcmDIR/$git_other ; git checkout master -- . ) 2>&1
   fi
 fi
 if [ $checkOut -eq 2 ] ; then
@@ -153,6 +178,18 @@ if [ $checkOut -eq 2 ] ; then
       cat $tmpFil ; rm -f $tmpFil
       exit
   fi
+  if test "x$addExp" != x ; then
+    echo "Make a clone of $git_other from repo: $git_repo ..."
+    ( cd $gcmDIR ; git clone $git_repo/${git_other}.git 2> $tmpFil )
+    retVal=$?
+    if test $retVal = 0 ; then
+      echo '  done' ; rm -f $tmpFil
+    else
+      echo " Error: 'git clone' returned: $retVal"
+      cat $tmpFil ; rm -f $tmpFil
+      exit
+    fi
+  fi
   if test -d $gcmDIR/verification ; then
     /usr/bin/find $gcmDIR -type d | xargs chmod g+rxs
     /usr/bin/find $gcmDIR -type f | xargs chmod g+r
@@ -165,21 +202,13 @@ if test -e $gcmDIR/verification ; then
     echo " dir $gcmDIR/verification exist" ; fi
   cd $gcmDIR/verification
   for exp2add in $addExp ; do
-    if test -d ${exp2add}/CVS ; then
-      echo "  update dir: $exp2add (from Contrib:verification_other)"
-      ( cd $exp2add ; $cmdCVS update -P -d ) 2>&1
-      retVal=$?
-      if test "x$retVal" != x0 ; then
-        echo "cvs update on '"`hostname`"' fail (return val=$retVal)"
-       #exit
-      fi
+    test -r $exp2add && /bin/rm -rf $exp2add
+    if test -d  ../$git_other/$exp2add ; then
+      echo "  add $exp2add link from $git_other"
+      ln -s ../$git_other/$exp2add .
     else
-      test -r $exp2add && /bin/rm -rf $exp2add
-      echo " add dir: $exp2add (from Contrib:verification_other)"
-      ( $cmdCVS co -P -d $exp2add \
-                     MITgcm_contrib/verification_other/$exp2add > /dev/null )
-      /usr/bin/find $exp2add -type d | xargs chmod g+rxs
-      /usr/bin/find $exp2add -type f | xargs chmod g+r
+      echo "  missing dir: $git_other/$exp2add"
+      continue
     fi
   done
 else
