first attempt of running testreport from git repository on stan

diff --git a/run_tests/sxace/mitgcmtestreport b/run_tests/sxace/mitgcmtestreport
--- a/run_tests/sxace/mitgcmtestreport
+++ b/run_tests/sxace/mitgcmtestreport
@@ -15,7 +15,7 @@
 #   if not, testreport will try to run the sx ace-code on the tx7 frontend
 #   which will fail inevitably and produce more errors, maybe we can
 #   have a flag that skips everything but the evaluation step to avoid this
-# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/sxace/mitgcmtestreport,v 1.2 2015/09/01 08:03:35 mlosch Exp $
+# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/sxace/mitgcmtestreport,v 1.3 2018/01/09 10:11:43 mlosch Exp $
 # $Name:  $
 
 # for some reason the module command is not available in a bash script on
@@ -52,6 +52,9 @@ selectexperiment='-t exp2'
 selectexperiment=''
 # download code into this directory
 TDIR=/ace/user/mlosch/tmp_$VENDOR
+gcmDIR=MITgcm
+git_repo='MITgcm'
+git_code='MITgcm'
 
 OPTFILE=../tools/build_options/SUPER-UX_SX-ACE_sxf90_awi
 #OPTFILE=/home/ace/mlosch/MITgcm/tools/build_options/SUPER-UX_SX-ACE_sxf90_awi
@@ -84,24 +87,61 @@ fi
 if [ -e $OUTFILE ]; then
   rm -r $OUTFILE
 fi
-if [ -e $TDIR/MITgcm ]; then
-# if availabe just update
-    cd $TDIR/MITgcm
-    cvs -q update -d -P >> cvs_co.log 2>&1
-    if [ "$?" != "0" ]; then
-	cat cvs_co.log
+
+# checkOut determines how much checking out is being done
+# checkOut = 3: new clone from GitHub and make a new copy
+# checkOut = 2: update (git pull) existing repo and make a new copy
+# checkOut = 1: skip update
+# checkOut = 0: use existing test code (if available otherwise switch to 1)
+
+checkOut=2
+
+tmpFil=$TDIR/error.out
+if [ $checkOut -le 1 ] ; then
+  if test -e $TDIR/${gcmDIR}/doc ; then
+    echo $TDIR/${gcmDIR}/doc 'exist'
+  else
+    echo -n $TDIR/${gcmDIR} 'missing ; '
+    checkOut=2
+    echo "will make a new copy ( checkOut=$checkOut )"
+  fi
+fi
+
+if [ $checkOut -ge 2 ] ; then
+  #---- cleaning:
+  cd $TDIR
+
+  #---- Make a new clone or update existing one:
+  if test -e ${gcmDIR}/.git/config ; then
+    echo "${gcmDIR}/.git/config exist"
+  else
+    echo -n "${gcmDIR}/.git/config 'missing, "
+    checkOut=3
+    echo "will get new clone ( checkOut=$checkOut )"
+  fi
+  if [ $checkOut -eq 3 ] ; then
+    echo -n "Removing old clone: $TDIR/${gcmDIR} ..."
+    test -e $TDIR/${gcmDIR}  &&  rm -rf $TDIR/${gcmDIR}
+    echo "  done"
+    echo -n "Make a new clone of $git_code from repo: $git_repo ..."
+    git clone https://github.com/$git_repo/${git_code}.git ${gcmDIR} 2> $tmpFil
+    retVal=$?
+    if test $retVal = 0 ; then
+       echo ' --> done!'
+       rm -f $tmpFil
+    else
+       echo " Error: 'git clone' returned: $retVal"
+       cat $tmpFil
+       rm -f $tmpFil
+       exit 2
     fi
+  else
+    echo "Updating current clone ( $git_code ) ..."
+    ( cd ${gcmDIR}; git checkout master ; git pull )
+    echo ' --> done!'
+  fi
 else
-# create directory and download code
-    if [ -e $TDIR ]; then
-	rm -rf $TDIR
-    fi
-    mkdir $TDIR
-    cd $TDIR
-    cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack co MITgcm > cvs_co.log 2>&1
-    if [ "$?" != "0" ]; then
-	cat cvs_co.log
-    fi
+  cd $TDIR
 fi
 
 cd $TDIR/MITgcm/verification
@@ -141,6 +181,7 @@ echo "***********************************************************" >> $MYOUTPUT
 echo " " >> $MYOUTPUT
 
 # now submit the job that actually runs all the experiments in one go
+echo "qsub $HERE/$JOBSCRIPT"
 qsub $HERE/$JOBSCRIPT
 # keep looking for the job in the job queues and wait until has disappeared
 jobruns=`qstat -n -u mlosch | grep "$JOBNAME"`
