minor updates
with less differences between "test_submit_*" scripts

diff --git a/run_tests/svante/test_submit_svante b/run_tests/svante/test_submit_svante
--- a/run_tests/svante/test_submit_svante
+++ b/run_tests/svante/test_submit_svante
@@ -51,6 +51,7 @@ logPfix='test_submit'
  QSUB="/usr/bin/sbatch"
  QLIST="/usr/bin/squeue -u $USER"
 #- and batch scripts:
+ scrDirNam="run_tests/$dNam"
  SUB_DIR="$HERE/$dNam"
  OUT_DIR="$HERE/output"
  LOG_FIL="$OUT_DIR/$logPfix."`date +%m%d`".log"
@@ -139,8 +140,6 @@ fi
 if [ -d ~/bin ]; then export PATH=$PATH:~/bin ; fi
 #- to get case insensitive "ls" (and order of tested experiments)
 export LC_ALL="en_US.UTF-8"
-#  Turn off stack limit for FIZHI & AD-tests
-ulimit -s unlimited
 
 if test -f /etc/profile.d/modules.sh    ; then . /etc/profile.d/modules.sh    ; fi
 if test -f /etc/profile.d/zz_modules.sh ; then . /etc/profile.d/zz_modules.sh ; fi
@@ -150,6 +149,7 @@ module add slurm
 module list 						>> $LOG_FIL 2>&1
 
 #---+----1----+----2----+----3----+----4----+----5----+----6----+----7-|--+----|
+
 if [ $updateTst -ge 1 ] ; then
   cd $HERE
 #-- Download/Update batch testing scripts:
@@ -194,14 +194,15 @@ if [ $updateTst -ge 1 ] ; then
   fi
   #-- symbolic-link as short-cut
   if test ! -e $dNam ; then
-    if test -d $git_test/run_tests/$dNam ; then
-      echo "  link '$git_test/run_tests/$dNam' to '$dNam'"	| tee -a $LOG_FIL
-      ln -s $git_test/run_tests/$dNam $dNam
+    if test -d $git_test/$scrDirNam ; then
+      echo "  link '$git_test/$scrDirNam' to '$dNam'"		| tee -a $LOG_FIL
+      ln -s $git_test/$scrDirNam $dNam
     fi
   fi
 fi #-- Done with Download/Update of testing scripts
 
 #---+----1----+----2----+----3----+----4----+----5----+----6----+----7-|--+----|
+
 if [ $updateSrc -ge 1 ] ; then
 #-- Download/Update reference version of MITgcm code:
 
@@ -279,8 +280,8 @@ if [ $updateSrc -ge 1 ] ; then
     ( cd $git_code ; git pull )				>> $LOG_FIL 2>&1
     retVal=$?
     if test "x$retVal" != x0 ; then echo ''
-         echo "'git pull' on '"`hostname`"' fail (return val=$retVal) => exit" | tee -a $LOG_FIL
-         exit 7
+       echo "'git pull' on '"`hostname`"' fail (return val=$retVal) => exit" | tee -a $LOG_FIL
+       exit 7
     else echo "  done"					| tee -a $LOG_FIL
     fi
     echo "  and checkout master:"			| tee -a $LOG_FIL
@@ -315,9 +316,9 @@ fi #-- Done with Download/Update of MITgcm code
 #---+----1----+----2----+----3----+----4----+----5----+----6----+----7-|--+----|
 
 if [ $submitJob -ge 1 ] ; then
-#-- leave srcDIR and go back to output dir
+#-- Submit batch test-scripts jobs : leave srcDIR and go back to output dir
   cd $OUT_DIR
-#-- now really do something:
+  #-- start job submission process
 
   JOB_LIST=$TEST_LIST
   NB_SUB_JOBS=0
@@ -328,14 +329,14 @@ if [ $submitJob -ge 1 ] ; then
     if test -f $SUB_DIR/$BATCH_SCRIPT ; then
       #- job name ( $JOB ) & output-file name ( $JOB.std??? ) must match
       #  definition within $BATCH_SCRIPT slurm script
-      JOB="${i}_tst"
+      JOB="${i}_tst" ; sJob=$JOB
       sJob=`printf "%8.8s" $JOB` #- squeue truncate name to only 1rst 8c
       job_exist=`$QLIST | grep $sJob | wc -l`
       if test "x_$job_exist" = x_0 ; then
         #-- move previous output file
         outList=`ls $JOB.std??? 2> /dev/null`
         if test "x$outList" != x ; then
-          echo -n " moving job $JOB old output files:"	| tee -a $LOG_FIL
+          echo -n " moving job '$JOB' old output files:"| tee -a $LOG_FIL
           if test -d $OUT_DIR/prev ; then
             for xx in $outList ; do
               pp=$OUT_DIR/prev/$xx ; echo -n " $xx"	| tee -a $LOG_FIL
@@ -347,7 +348,7 @@ if [ $submitJob -ge 1 ] ; then
           else
             echo " <-- missing dir $OUT_DIR/prev"	| tee -a $LOG_FIL
           fi
-        else echo " no old output files from job '$JOB'" | tee -a $LOG_FIL
+        else echo " no old output files from job '$JOB'"| tee -a $LOG_FIL
         fi
         #-- submit job
           echo -n "--> $JOB : $BATCH_SCRIPT , "		| tee -a $LOG_FIL
@@ -363,11 +364,12 @@ if [ $submitJob -ge 1 ] ; then
        echo 'no file:' $BATCH_SCRIPT 'to submit'	| tee -a $LOG_FIL
     fi
   done
-  #echo "info-sub-list: NB_SUB_JOBS='$NB_SUB_JOBS'"	>> $LOG_FIL
   echo "Submitted $NB_SUB_JOBS jobs from dir: $SUB_DIR"	| tee -a $LOG_FIL
 
-fi
+fi #-- Done with submitting jobs
+
 #---+----1----+----2----+----3----+----4----+----5----+----6----+----7-|--+----|
+
 echo -n '-- Finished at: '				| tee -a $LOG_FIL
 date							| tee -a $LOG_FIL
 exit 0
