- change name of MPI test from "MPI" to "Mpi" (ifcMpi, pgiMpi)   (similar to engaging test) - minor changes (use "dblTr" in all scripts) to make these scripts   more similars to each other and more similar to engaging scripts

diff --git a/run_tests/svante/test_svante_ifc_mpi b/run_tests/svante/test_svante_ifc_mpi
--- a/run_tests/svante/test_svante_ifc_mpi
+++ b/run_tests/svante/test_svante_ifc_mpi
@@ -1,16 +1,16 @@
 #!/bin/bash
-#SBATCH -J ifcMPI_tst
+#SBATCH -J ifcMpi_tst
 #SBATCH -p edr
 #SBATCH -t 23:30:00
 #SBATCH --mem-per-cpu 4000
 #SBATCH -N 1
 #SBATCH --tasks-per-node 6
 # #SBATCH -x curly,larry,moe,shemp
-#SBATCH -e /home/jm_c/test_svante/output/ifcMPI_tst.stderr
-#SBATCH -o /home/jm_c/test_svante/output/ifcMPI_tst.stdout
+#SBATCH -e /home/jm_c/test_svante/output/ifcMpi_tst.stderr
+#SBATCH -o /home/jm_c/test_svante/output/ifcMpi_tst.stdout
 #SBATCH --no-requeue
 
-# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/svante/test_svante_ifc_mpi,v 1.18 2022/04/04 04:34:38 jmc Exp $
+# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/svante/test_svante_ifc_mpi,v 1.19 2022/08/17 14:44:50 jmc Exp $
 # $Name:  $
 
 if test -f /etc/profile.d/modules.sh    ; then . /etc/profile.d/modules.sh    ; fi
@@ -47,8 +47,8 @@ srcCode="MITgcm_today"
  #git_repo="git://github.com/$git_repo"
  #git_repo="git@github.com:$git_repo"
 
-typ='' ; addExp='' ; skipExp=''
-sfx='ifcMPI'
+dblTr=0 ; typ='' ; addExp='' ; skipExp=''
+sfx='ifcMpi'; dblTr=1
  module add intel/2021.4.0
  module add openmpi
 #module add netcdf
@@ -57,18 +57,18 @@ sfx='ifcMPI'
 #- needed for DIVA with MPI:
 #export MPI_INC_DIR=$INC_MPI
  options="$typ -MPI 6"
-#options="-j 2 $options"
-#- need this to get "staf":
-#export PATH="$PATH:$HOME/bin"
+#- need this to get "staf" & "do_make_syntax.sh":
+ export PATH="$PATH:$HOME/bin"
 
 gcmDIR="MITgcm_$sfx"
 dAlt=`date +%d` ; dAlt=`expr $dAlt % 3`
 if [ $dAlt -eq 1 ] ; then options="$options -fast"
 else options="$options -devel" ; fi
+if test "x$skipExp" != x ; then skipExp=`echo $skipExp | sed 's/^ *//'` ; fi
 
 checkOut=2 ; #options="$options -do"
-#options="$options -nc" ; checkOut=1
-#options="$options -q"  ; checkOut=0
+#options="$options -nc" ; checkOut=1 ; dblTr=0
+#options="$options -q"  ; checkOut=0 ; dblTr=0
 
 echo "cd $TST_DISK ; pwd (x1)"
 cd $TST_DISK
@@ -76,15 +76,15 @@ pwd ; ls -l
 if test ! -d $TST_DIR ; then sleep 5 ; pwd ; ls -l ; fi
 if test ! -d $TST_DIR ; then
    echo -n "Creating a working dir: $TST_DIR ..."
-  #/bin/rm -rf $TST_DIR
    mkdir $TST_DIR
    retVal=$?
    if test "x$retVal" != x0 ; then
-      echo " FAIL"
-      echo "Error: unable to make dir: $TST_DIR (err=$retVal ) from $TST_DISK --> Exit"
-      exit 1
-   else echo " done"
-   fi
+      if test ! -d $TST_DIR ; then
+         echo " FAIL"
+         echo "Error: unable to make dir: $TST_DIR (err=$retVal ) from $TST_DISK --> Exit"
+         exit 1
+      else echo " FAIL but dir now exists ! -> continue" ; fi
+   else echo " done" ; fi
 fi
 echo "start from DIR='$TST_DISK/$TST_DIR' at: "`date`
 cd $TST_DIR
@@ -114,6 +114,18 @@ if [ $dsp -gt 99 ] ; then
   exit
 fi
 
+if [ $checkOut -eq 1 ] ; then
+  if test ! -e $gcmDIR/.git/config ; then
+    echo "no file: $gcmDIR/.git/config => try to download a fresh clone"
+    checkOut=2
+  fi
+  if test "x$addExp" != x ; then
+    if test ! -e $gcmDIR/$git_other/.git/config ; then
+      echo "no file: $gcmDIR/$git_other/.git/config => try a fresh clone"
+      checkOut=2
+    fi
+  fi
+fi
 if [ $checkOut -eq 1 ] ; then
     echo "cleaning output from $gcmDIR/verification :"
 #- remove previous output tar files and tar & remove previous output-dir
@@ -195,7 +207,7 @@ if [ $checkOut -eq 2 ] ; then
   else echo " dir: $srcDIR/$srcCode missing => exit" ; exit ; fi
 fi
 
-#- change dir to $gcmDIR/verification dir:
+#- change dir to $gcmDIR/verification + add link for additional experiments:
 if test -e $gcmDIR/verification ; then
   if [ $checkOut -lt 2 ] ; then
     echo " dir $gcmDIR/verification exist" ; fi
@@ -233,42 +245,37 @@ else
   exit
 fi
 
-if [ $checkOut -ge 1 ] ; then
- if [ $dAlt -eq 1 ] ; then
+if [ $dblTr -eq 1 ] ; then
+ if [ $dAlt -ne 1 ] ; then
   echo ''
-  #- 1) just compile ("-nr"), using "-j 2" to speed up
-  echo ./testreport $options -of $OPTFILE -skd \'$skipExp\' \
-    -j 4 -nr -odir ${dNam}-$sfx
-  ./testreport $options -of $OPTFILE -skd "$skipExp" \
-    -j 4 -nr -odir ${dNam}-$sfx
-  nFc=`grep -c '^Y . N N ' tr_out.txt`
-  echo " <= fail to compile $nFc experiments"
- else
-  echo ''
-  #- 0) just make all module header ( *__genmod.mod files) using modified Makefile
+#- 0) just make all module header ( *__genmod.mod files) using modified Makefile
   echo ./testreport $options -of $OPTFILE -skd \'$skipExp\' \
     -j 4 -repl_mk do_make_syntax.sh -obj -dd
   ./testreport $options -of $OPTFILE -skd "$skipExp" \
     -j 4 -repl_mk do_make_syntax.sh -obj -dd 2>&1
+  options="$options -q"
+ fi
+
   echo ''
-  #- 1) just compile ("-nr"), using "-j 2" to speed up
+#- 1) just compile ("-nr"), using "-j 4" to speed up
   echo ./testreport $options -of $OPTFILE -skd \'$skipExp\' \
-    -j 4 -nr -q -odir ${dNam}-$sfx
+    -j 4 -nr -odir ${dNam}-$sfx
   ./testreport $options -of $OPTFILE -skd "$skipExp" \
-    -j 4 -nr -q -odir ${dNam}-$sfx
+    -j 4 -nr -odir ${dNam}-$sfx
   nFc=`grep -c '^Y . N N ' tr_out.txt`
   echo " <= fail to compile $nFc experiments"
- fi
+ if [ $dAlt -eq 1 ] ; then options="$options -q" ; fi
 fi
 
   echo ''
-  #- 2) run and report results ; also finish to compile those who failed with "-j"
+#- 2) run and report results ; also finish to compile those who failed with "-j"
   echo ./testreport $options -of $OPTFILE -skd \'$skipExp\' \
-    -q -odir ${dNam}-$sfx -send \'$SEND\' -sd $SavD -a jm_c@mitgcm.org
+    -odir ${dNam}-$sfx -send \'$SEND\' -sd $SavD -a jm_c@mitgcm.org
   ./testreport $options -of $OPTFILE -skd "$skipExp" \
-    -q -odir ${dNam}-$sfx -send "$SEND" -sd $SavD -a jm_c@mitgcm.org
+    -odir ${dNam}-$sfx -send "$SEND" -sd $SavD -a jm_c@mitgcm.org
+
   echo ''
-  #- 3) test restart and report results
+#- 3) test restart and report results
   echo ../tools/do_tst_2+2 -mpi \
     -o ${dNam}-$sfx -send \'$SEND\' -sd $SavD -a jm_c@mitgcm.org
   ../tools/do_tst_2+2 -mpi \
diff --git a/run_tests/svante/test_svante_pgi_adm b/run_tests/svante/test_svante_pgi_adm
--- a/run_tests/svante/test_svante_pgi_adm
+++ b/run_tests/svante/test_svante_pgi_adm
@@ -10,7 +10,7 @@
 #SBATCH -o /home/jm_c/test_svante/output/pgiAdm_tst.stdout
 #SBATCH --no-requeue
 
-# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/svante/test_svante_pgi_adm,v 1.13 2020/09/21 20:34:32 jmc Exp $
+# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/svante/test_svante_pgi_adm,v 1.15 2022/09/21 16:54:25 jmc Exp $
 # $Name:  $
 
 if test -f /etc/profile.d/modules.sh    ; then . /etc/profile.d/modules.sh    ; fi
@@ -47,7 +47,7 @@ srcCode="MITgcm_today"
  #git_repo="git://github.com/$git_repo"
  #git_repo="git@github.com:$git_repo"
 
-typ='' ; addExp='' ; skipExp=''
+dblTr=0 ; typ='' ; addExp='' ; skipExp=''
 sfx='pgiAdm'; typ='-adm'
  module add pgi/16.9
  module add openmpi
@@ -63,6 +63,7 @@ gcmDIR="MITgcm_$sfx"
 dAlt=`date +%d` ; dAlt=`expr $dAlt % 3`
 if [ $dAlt -eq 1 ] ; then options="$options -fast"
 else options="$options -devel" ; fi
+if test "x$skipExp" != x ; then skipExp=`echo $skipExp | sed 's/^ *//'` ; fi
 
 checkOut=2 ; #options="$options -do"
 #options="$options -nc" ; checkOut=1
@@ -74,15 +75,15 @@ pwd ; ls -l
 if test ! -d $TST_DIR ; then sleep 5 ; pwd ; ls -l ; fi
 if test ! -d $TST_DIR ; then
    echo -n "Creating a working dir: $TST_DIR ..."
-  #/bin/rm -rf $TST_DIR
    mkdir $TST_DIR
    retVal=$?
    if test "x$retVal" != x0 ; then
-      echo " FAIL"
-      echo "Error: unable to make dir: $TST_DIR (err=$retVal ) from $TST_DISK --> Exit"
-      exit 1
-   else echo " done"
-   fi
+      if test ! -d $TST_DIR ; then
+         echo " FAIL"
+         echo "Error: unable to make dir: $TST_DIR (err=$retVal ) from $TST_DISK --> Exit"
+         exit 1
+      else echo " FAIL but dir now exists ! -> continue" ; fi
+   else echo " done" ; fi
 fi
 echo "start from DIR='$TST_DISK/$TST_DIR' at: "`date`
 cd $TST_DIR
@@ -112,6 +113,18 @@ if [ $dsp -gt 99 ] ; then
   exit
 fi
 
+if [ $checkOut -eq 1 ] ; then
+  if test ! -e $gcmDIR/.git/config ; then
+    echo "no file: $gcmDIR/.git/config => try to download a fresh clone"
+    checkOut=2
+  fi
+  if test "x$addExp" != x ; then
+    if test ! -e $gcmDIR/$git_other/.git/config ; then
+      echo "no file: $gcmDIR/$git_other/.git/config => try a fresh clone"
+      checkOut=2
+    fi
+  fi
+fi
 if [ $checkOut -eq 1 ] ; then
     echo "cleaning output from $gcmDIR/verification :"
 #- remove previous output tar files and tar & remove previous output-dir
@@ -191,7 +204,7 @@ if [ $checkOut -eq 2 ] ; then
   else echo " dir: $srcDIR/$srcCode missing => exit" ; exit ; fi
 fi
 
-#- change dir to $gcmDIR/verification dir:
+#- change dir to $gcmDIR/verification + add link for additional experiments:
 if test -e $gcmDIR/verification ; then
   if [ $checkOut -lt 2 ] ; then
     echo " dir $gcmDIR/verification exist" ; fi
@@ -229,15 +242,27 @@ else
   exit
 fi
 
-echo ''
-echo ./testreport $options -of $OPTFILE -skd \'$skipExp\' \
-  -odir ${dNam}-$sfx -send \'$SEND\' -sd $SavD -a jm_c@mitgcm.org
-./testreport $options -of $OPTFILE -skd "$skipExp" \
-  -odir ${dNam}-$sfx -send "$SEND" -sd $SavD -a jm_c@mitgcm.org
+if [ $dblTr -eq 1 ] ; then
+  echo ''
+#- 1) just compile ("-nr"), using "-j 4" to speed up
+  echo ./testreport $options -of $OPTFILE -skd \'$skipExp\' \
+    -j 4 -nr -odir ${dNam}-$sfx
+  ./testreport $options -of $OPTFILE -skd "$skipExp" \
+    -j 4 -nr -odir ${dNam}-$sfx
+  options="$options -q"
+fi
 
-#echo ''
-#echo ../tools/do_tst_2+2 -mpi \
-#  -o ${dNam}-$sfx -send \'$SEND\' -sd $SavD -a jm_c@mitgcm.org
-#../tools/do_tst_2+2 -mpi \
-#  -o ${dNam}-$sfx -send "$SEND" -sd $SavD -a jm_c@mitgcm.org
+  echo ''
+#- 2) run and report results ; also finish to compile those who failed with "-j"
+  echo ./testreport $options -of $OPTFILE -skd \'$skipExp\' \
+    -odir ${dNam}-$sfx -send \'$SEND\' -sd $SavD -a jm_c@mitgcm.org
+  ./testreport $options -of $OPTFILE -skd "$skipExp" \
+    -odir ${dNam}-$sfx -send "$SEND" -sd $SavD -a jm_c@mitgcm.org
+
+# echo ''
+#- 3) test restart and report results
+# echo ../tools/do_tst_2+2 -mpi \
+#   -o ${dNam}-$sfx -send \'$SEND\' -sd $SavD -a jm_c@mitgcm.org
+# ../tools/do_tst_2+2 -mpi \
+#   -o ${dNam}-$sfx -send "$SEND" -sd $SavD -a jm_c@mitgcm.org
 
