Cleaning: remove all CVS command and put git command and add bits for partial update (checkOut=1) and additional exp (addExp), even though not currently used

diff --git a/run_tests/svante/test_svante_ifc_mpi b/run_tests/svante/test_svante_ifc_mpi
--- a/run_tests/svante/test_svante_ifc_mpi
+++ b/run_tests/svante/test_svante_ifc_mpi
@@ -10,7 +10,7 @@
 #SBATCH -o /home/jm_c/test_svante/output/ifcMPI_tst.stdout
 #SBATCH --no-requeue
 
-# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/svante/test_svante_ifc_mpi,v 1.14 2018/03/23 13:58:23 jmc Exp $
+# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/svante/test_svante_ifc_mpi,v 1.15 2018/06/12 21:42:21 jmc Exp $
 # $Name:  $
 
 if test -f /etc/profile.d/modules.sh    ; then . /etc/profile.d/modules.sh    ; fi
@@ -36,6 +36,39 @@ TST_DIR="$TST_DISK/test_${dNam}"
 srcDIR=$HERE
 srcCode="MITgcm_today"
 
+#- following lines are not used here:
+  cmdCVS='cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack -q'
+#- which GitHub repository to use and how to access it:
+  git_repo='MITgcm'; git_code='MITgcm' ; git_other='verification_other'
+ #git_repo='altMITgcm'; #git_code='MITgcm66h'
+#--
+  git_repo="https://github.com/$git_repo"
+ #git_repo="git://github.com/$git_repo"
+ #git_repo="git@github.com:$git_repo"
+
+typ='' ; addExp='' ; skipExp=''
+sfx='ifcMPI'
+ module add intel/2017.0.1
+ module add openmpi
+#module add netcdf
+ OPTFILE="../tools/build_options/linux_amd64_ifort11"
+ export GENERIC='on' # <-- to prevent the use of "-xHost" option
+#- needed for DIVA with MPI:
+#export MPI_INC_DIR=$INC_MPI
+ options="$typ -MPI 6"
+#options="-j 2 $options"
+#- need this to get "staf":
+#export PATH="$PATH:$HOME/bin"
+
+gcmDIR="MITgcm_$sfx"
+dAlt=`date +%d` ; dAlt=`expr $dAlt % 3`
+if [ $dAlt -eq 1 ] ; then options="$options -fast"
+else options="$options -devel" ; fi
+
+checkOut=2 ; #options="$options -do"
+#options="$options -nc" ; checkOut=1
+#options="$options -q"  ; checkOut=0
+
 echo "cd $TST_DISK ; pwd (x2)"
 cd $TST_DISK
 pwd
@@ -53,28 +86,6 @@ echo "start from TST_DIR='$TST_DIR' at: "`date`
 cd $TST_DIR
 pwd
 
-typ='' ; addExp='' ; skipExp=''
-sfx='ifcMPI'
- module add intel/2017.0.1
- module add openmpi
-#module add netcdf
- OPTFILE="../tools/build_options/linux_amd64_ifort11"
- export GENERIC='on' # <-- to prevent the use of "-xHost" option
-#- needed for DIVA with MPI:
-#export MPI_INC_DIR=$INC_MPI
- options="$typ -MPI 6"
-#options="-j 2 $options"
-#- need this to get "staf":
-#export PATH="$PATH:$HOME/bin"
-
-dAlt=`date +%d` ; dAlt=`expr $dAlt % 3`
-#if [ $dAlt -eq 1 ] ; then options="$options -fast"
-#else options="$options -devel" ; fi
-
-checkOut=2 ; #options="$options -do"
-#options="$options -nc" ; checkOut=1
-#options="$options -q"  ; checkOut=0
-
 NSLOTS=$SLURM_NTASKS
 THEDATE=`date`
 echo '********************************************************************************'
@@ -89,8 +100,6 @@ echo '======= modules ==========================================================
 module list 2>&1
 echo '================================================================================'
 
-cmdCVS='cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack -q'
-gcmDIR="MITgcm_$sfx"
 #- check for disk space: relative space (99%) or absolute (10.G):
 dsp=`df -P . | tail -1 | awk '{print $5}' | sed 's/%$//'`
 if [ $dsp -gt 99 ] ; then
@@ -100,8 +109,8 @@ if [ $dsp -gt 99 ] ; then
   df .
   exit
 fi
+
 if [ $checkOut -eq 1 ] ; then
-  if test -d $gcmDIR/CVS ; then
     echo "cleaning output from $gcmDIR/verification :"
 #- remove previous output tar files and tar & remove previous output-dir
     /bin/rm -f $gcmDIR/verification/??_${dNam}-${sfx}_????????_?.tar.gz
@@ -118,27 +127,47 @@ if [ $checkOut -eq 1 ] ; then
           fi
         fi
       done )
+    echo "clean tst_2+2 + testreport output (+ Makefile_syntax files)"
     ( cd $gcmDIR/verification ; ../tools/do_tst_2+2 -clean )
     ( cd $gcmDIR/verification ; ./testreport $typ -clean )
-    echo "cvs update of dir $gcmDIR :"
-    ( cd $gcmDIR ; $cmdCVS update -P -d ) 2>&1
+    ( cd $gcmDIR/verification ; rm -f */build/Makefile_syntax )
+    ( cd $gcmDIR/verification ; rm -f */build/port_rand.i */build/ptracers_set_iolabel.i )
+    if test "x$addExp" != x ; then
+      ( cd $gcmDIR/verification
+        listD=`ls -o | grep '^l' | awk '{print $8}' 2> /dev/null`
+        echo " + remove local links: $listD"
+        /bin/rm -f $listD
+      )
+    fi
+    echo "Update $git_code code in dir $gcmDIR :"
+    ( cd $gcmDIR ; git pull ) 2>&1
     retVal=$?
     if test "x$retVal" != x0 ; then
-       echo "cvs update on '"`hostname`"' fail (return val=$retVal) => exit"
+       echo "git pull on '"`hostname`"' fail (return val=$retVal) => exit"
        exit
     fi
-  else
-    echo "no dir: $gcmDIR/CVS => try a fresh check-out"
-    checkOut=2
+    echo "  and checkout master:"
+    ( cd $gcmDIR ; git checkout master -- . ) 2>&1
+  if test "x$addExp" != x ; then
+    echo "Update $git_other code in dir $gcmDIR/$git_other :"
+    ( cd $gcmDIR/$git_other ; git pull ) 2>&1
+    retVal=$?
+    if test "x$retVal" != x0 ; then
+       echo "git pull on '"`hostname`"' fail (return val=$retVal) => exit"
+       exit
+    fi
+    echo "  and checkout master:"
+    ( cd $gcmDIR/$git_other ; git checkout master -- . ) 2>&1
   fi
 fi
+
 if [ $checkOut -eq 2 ] ; then
   if test -e $gcmDIR ; then
     echo -n "Removing working copy: $gcmDIR ..."
     rm -rf $gcmDIR
     echo "  done"
   fi
-# make a local copy (instead of using CVS):
+# make a local copy (instead of making a new clone):
   today=`date +%Y%m%d`
   nCount=0; updFile="${srcDIR}/updated_code"
   updDate=0 ; test -f $updFile && updDate=`cat $updFile`
@@ -167,13 +196,41 @@ if test -e $gcmDIR/verification ; then
   if [ $checkOut -lt 2 ] ; then
     echo " dir $gcmDIR/verification exist" ; fi
   cd $gcmDIR/verification
+  for exp2add in $addExp ; do
+    test -r $exp2add && /bin/rm -rf $exp2add
+    if test -d  ../$git_other/$exp2add ; then
+      echo "  add $exp2add link from $git_other"
+      ln -s ../$git_other/$exp2add .
+      if test $exp2add = 'global_oce_cs32' ; then
+        echo "    link dir 'other_input/core2_cnyf' in here"
+        ( cd ../${git_other}/${exp2add}
+          test -L core2_cnyf && /bin/rm -f core2_cnyf
+          ln -s ../../../other_input/core2_cnyf . )
+      fi
+      if test $exp2add = 'global_oce_llc90' ; then
+        echo "    link dir 'other_input/gael_oce_llc90_input' to 'input_fields'"
+        ( cd ../${git_other}/${exp2add}
+          test -L input_fields && /bin/rm -f input_fields
+          ln -s  ../../../other_input/gael_oce_llc90_input input_fields
+        echo "    link dirs: 'core2_cnyf' & 'global_oce_input_fields/*' in input_verifs"
+          test ! -e input_verifs && mkdir input_verifs
+          ( cd input_verifs ; /bin/rm -f *
+            ln -s ../../../../other_input/core2_cnyf .
+            ln -s ../../../../other_input/global_oce_input_fields/* . )
+        )
+      fi
+    else
+      echo "  missing dir: $git_other/$exp2add"
+      continue
+    fi
+  done
 else
   echo "no dir: $gcmDIR/verification => exit"
   exit
 fi
 
-if [ $dAlt -eq 1 ] ; then
-  options="$options -fast"
+if [ $checkOut -ge 1 ] ; then
+ if [ $dAlt -eq 1 ] ; then
   echo ''
   #- 1) just compile ("-nr"), using "-j 2" to speed up
   echo ./testreport $options -of $OPTFILE -skd \'$skipExp\' \
@@ -182,8 +239,7 @@ if [ $dAlt -eq 1 ] ; then
     -j 4 -nr -odir ${dNam}-$sfx
   nFc=`grep -c '^Y . N N ' tr_out.txt`
   echo " <= fail to compile $nFc experiments"
-else
-  options="$options -devel"
+ else
   echo ''
   #- 0) just make all module header ( *__genmod.mod files) using modified Makefile
   echo ./testreport $options -of $OPTFILE -skd \'$skipExp\' \
@@ -198,7 +254,9 @@ else
     -j 4 -nr -q -odir ${dNam}-$sfx
   nFc=`grep -c '^Y . N N ' tr_out.txt`
   echo " <= fail to compile $nFc experiments"
+ fi
 fi
+
   echo ''
   #- 2) run and report results ; also finish to compile those who failed with "-j"
   echo ./testreport $options -of $OPTFILE -skd \'$skipExp\' \
diff --git a/run_tests/svante/test_svante_pgi_adm b/run_tests/svante/test_svante_pgi_adm
--- a/run_tests/svante/test_svante_pgi_adm
+++ b/run_tests/svante/test_svante_pgi_adm
@@ -10,7 +10,7 @@
 #SBATCH -o /home/jm_c/test_svante/output/pgiAdm_tst.stdout
 #SBATCH --no-requeue
 
-# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/svante/test_svante_pgi_adm,v 1.10 2018/02/05 13:36:05 jmc Exp $
+# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/svante/test_svante_pgi_adm,v 1.11 2018/06/12 21:42:21 jmc Exp $
 # $Name:  $
 
 if test -f /etc/profile.d/modules.sh    ; then . /etc/profile.d/modules.sh    ; fi
@@ -36,6 +36,37 @@ TST_DIR="$TST_DISK/test_${dNam}"
 srcDIR=$HERE
 srcCode="MITgcm_today"
 
+#- following lines are not used here:
+  cmdCVS='cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack -q'
+#- which GitHub repository to use and how to access it:
+  git_repo='MITgcm'; git_code='MITgcm' ; git_other='verification_other'
+ #git_repo='altMITgcm'; #git_code='MITgcm66h'
+#--
+  git_repo="https://github.com/$git_repo"
+ #git_repo="git://github.com/$git_repo"
+ #git_repo="git@github.com:$git_repo"
+
+typ='' ; addExp='' ; skipExp=''
+sfx='pgiAdm'; typ='-adm'
+ module add pgi/16.9
+ module add openmpi
+ module add netcdf
+ OPTFILE="../tools/build_options/linux_amd64_pgf77"
+#- needed for DIVA with MPI:
+ export MPI_INC_DIR="/home/software/pgi/16.9/linux86-64/2016/mpi/openmpi-1.10.2/include"
+ options="$typ -MPI 6"
+#- need this to get "staf":
+ export PATH="$PATH:$HOME/bin"
+
+gcmDIR="MITgcm_$sfx"
+dAlt=`date +%d` ; dAlt=`expr $dAlt % 3`
+if [ $dAlt -eq 1 ] ; then options="$options -fast"
+else options="$options -devel" ; fi
+
+checkOut=2 ; #options="$options -do"
+#options="$options -nc" ; checkOut=1
+#options="$options -q"  ; checkOut=0
+
 echo "cd $TST_DISK ; pwd (x2)"
 cd $TST_DISK
 pwd
@@ -53,26 +84,6 @@ echo "start from TST_DIR='$TST_DIR' at: "`date`
 cd $TST_DIR
 pwd
 
-typ='' ; addExp='' ; skipExp=''
-sfx='pgiAdm'; typ='-adm'
- module add pgi/16.9
- module add openmpi
- module add netcdf
- OPTFILE="../tools/build_options/linux_amd64_pgf77"
-#- needed for DIVA with MPI:
- export MPI_INC_DIR="/home/software/pgi/16.9/linux86-64/2016/mpi/openmpi-1.10.2/include"
- options="$typ -MPI 6"
-#- need this to get "staf":
- export PATH="$PATH:$HOME/bin"
-
-dAlt=`date +%d` ; dAlt=`expr $dAlt % 3`
-if [ $dAlt -eq 1 ] ; then options="$options -fast"
-else options="$options -devel" ; fi
-
-checkOut=2 ; #options="$options -do"
-#options="$options -nc" ; checkOut=1
-#options="$options -q"  ; checkOut=0
-
 NSLOTS=$SLURM_NTASKS
 THEDATE=`date`
 echo '********************************************************************************'
@@ -87,8 +98,6 @@ echo '======= modules ==========================================================
 module list 2>&1
 echo '================================================================================'
 
-cmdCVS='cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack -q'
-gcmDIR="MITgcm_$sfx"
 #- check for disk space: relative space (99%) or absolute (10.G):
 dsp=`df -P . | tail -1 | awk '{print $5}' | sed 's/%$//'`
 if [ $dsp -gt 99 ] ; then
@@ -98,8 +107,8 @@ if [ $dsp -gt 99 ] ; then
   df .
   exit
 fi
+
 if [ $checkOut -eq 1 ] ; then
-  if test -d $gcmDIR/CVS ; then
     echo "cleaning output from $gcmDIR/verification :"
 #- remove previous output tar files and tar & remove previous output-dir
     /bin/rm -f $gcmDIR/verification/??_${dNam}-${sfx}_????????_?.tar.gz
@@ -116,27 +125,45 @@ if [ $checkOut -eq 1 ] ; then
           fi
         fi
       done )
-    ( cd $gcmDIR/verification ; ../tools/do_tst_2+2 -clean )
+    echo "clean testreport output"
+  # ( cd $gcmDIR/verification ; ../tools/do_tst_2+2 -clean )
     ( cd $gcmDIR/verification ; ./testreport $typ -clean )
-    echo "cvs update of dir $gcmDIR :"
-    ( cd $gcmDIR ; $cmdCVS update -P -d ) 2>&1
+    if test "x$addExp" != x ; then
+      ( cd $gcmDIR/verification
+        listD=`ls -o | grep '^l' | awk '{print $8}' 2> /dev/null`
+        echo " + remove local links: $listD"
+        /bin/rm -f $listD
+      )
+    fi
+    echo "Update $git_code code in dir $gcmDIR :"
+    ( cd $gcmDIR ; git pull ) 2>&1
     retVal=$?
     if test "x$retVal" != x0 ; then
-       echo "cvs update on '"`hostname`"' fail (return val=$retVal) => exit"
+       echo "git pull on '"`hostname`"' fail (return val=$retVal) => exit"
        exit
     fi
-  else
-    echo "no dir: $gcmDIR/CVS => try a fresh check-out"
-    checkOut=2
+    echo "  and checkout master:"
+    ( cd $gcmDIR ; git checkout master -- . ) 2>&1
+  if test "x$addExp" != x ; then
+    echo "Update $git_other code in dir $gcmDIR/$git_other :"
+    ( cd $gcmDIR/$git_other ; git pull ) 2>&1
+    retVal=$?
+    if test "x$retVal" != x0 ; then
+       echo "git pull on '"`hostname`"' fail (return val=$retVal) => exit"
+       exit
+    fi
+    echo "  and checkout master:"
+    ( cd $gcmDIR/$git_other ; git checkout master -- . ) 2>&1
   fi
 fi
+
 if [ $checkOut -eq 2 ] ; then
   if test -e $gcmDIR ; then
     echo -n "Removing working copy: $gcmDIR ..."
     rm -rf $gcmDIR
     echo "  done"
   fi
-# make a local copy (instead of using CVS):
+# make a local copy (instead of making a new clone):
   today=`date +%Y%m%d`
   nCount=0; updFile="${srcDIR}/updated_code"
   updDate=0 ; test -f $updFile && updDate=`cat $updFile`
@@ -158,23 +185,6 @@ if [ $checkOut -eq 2 ] ; then
     cp -pra $srcDIR/$srcCode $gcmDIR
     echo "  done"
   else echo " dir: $srcDIR/$srcCode missing => exit" ; exit ; fi
-# cvs co MITgcm
- #echo "Downloading using '$cmdCVS co -P -d $gcmDIR MITgcm' ..."
- #$cmdCVS co -P -d $gcmDIR MITgcm > /dev/null
- #retVal=$?
- #if test "x$retVal" != x0 ; then
- #    echo "cvs co on '"`hostname`"' fail (return val=$retVal) => exit"
- #    exit
- #else echo "  done" ; fi
- #if test -d $gcmDIR/verification ; then
- #  for exp2add in $addExp ; do
- #    echo " add dir: $exp2add (from Contrib:verification_other)"
- #    ( cd $gcmDIR/verification ; $cmdCVS co -P -d $exp2add \
- #                   MITgcm_contrib/verification_other/$exp2add > /dev/null )
- #  done
- #  /usr/bin/find $gcmDIR -type d | xargs chmod g+rxs
- #  /usr/bin/find $gcmDIR -type f | xargs chmod g+r
- #fi
 fi
 
 #- change dir to $gcmDIR/verification dir:
@@ -182,6 +192,34 @@ if test -e $gcmDIR/verification ; then
   if [ $checkOut -lt 2 ] ; then
     echo " dir $gcmDIR/verification exist" ; fi
   cd $gcmDIR/verification
+  for exp2add in $addExp ; do
+    test -r $exp2add && /bin/rm -rf $exp2add
+    if test -d  ../$git_other/$exp2add ; then
+      echo "  add $exp2add link from $git_other"
+      ln -s ../$git_other/$exp2add .
+      if test $exp2add = 'global_oce_cs32' ; then
+        echo "    link dir 'other_input/core2_cnyf' in here"
+        ( cd ../${git_other}/${exp2add}
+          test -L core2_cnyf && /bin/rm -f core2_cnyf
+          ln -s ../../../other_input/core2_cnyf . )
+      fi
+      if test $exp2add = 'global_oce_llc90' ; then
+        echo "    link dir 'other_input/gael_oce_llc90_input' to 'input_fields'"
+        ( cd ../${git_other}/${exp2add}
+          test -L input_fields && /bin/rm -f input_fields
+          ln -s  ../../../other_input/gael_oce_llc90_input input_fields
+        echo "    link dirs: 'core2_cnyf' & 'global_oce_input_fields/*' in input_verifs"
+          test ! -e input_verifs && mkdir input_verifs
+          ( cd input_verifs ; /bin/rm -f *
+            ln -s ../../../../other_input/core2_cnyf .
+            ln -s ../../../../other_input/global_oce_input_fields/* . )
+        )
+      fi
+    else
+      echo "  missing dir: $git_other/$exp2add"
+      continue
+    fi
+  done
 else
   echo "no dir: $gcmDIR/verification => exit"
   exit
