change to use new code repository on GitHub

diff --git a/run_tests/other/test_local b/run_tests/other/test_local
--- a/run_tests/other/test_local
+++ b/run_tests/other/test_local
@@ -1,6 +1,6 @@
 #! /usr/bin/env bash
 
-# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/other/test_local,v 1.4 2017/07/28 17:02:18 jmc Exp $
+# $Header: /u/gcmpack/MITgcm_contrib/test_scripts/other/test_local,v 1.5 2018/01/05 22:25:25 jmc Exp $
 # $Name:  $
 
 if test $# = 0 ; then
@@ -36,7 +36,13 @@ fi
 #- Turn off stack limit for FIZHI & AD-tests
 ulimit -s unlimited
 #- method to acces CVS:
-cmdCVS='cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack -q'
+  cmdCVS='cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack -q'
+#- and which GitHub repository to use:
+  git_repo='MITgcm';  git_code='MITgcm'
+ #git_repo='altMITgcm'; #git_code='MITgcm66h'
+#- other settings:
+tmpFil="/tmp/"`basename $0`".$$"
+mAddr='jm_c@mitgcm.org'
 
 #-- for now, cannot mix ifort/gfortran tests:
 gfort=1
@@ -63,61 +69,73 @@ fi
 for tt in $tst_list
 do
 
+  gcmDIR="MITgcm_$tt"
   echo "=========================================================================="
 # set -x
   rm -f tr_clean_$tt.log
   echo $tt | grep '^.ad' > /dev/null 2>&1 ; fwd=$?
   echo " testing tt= $tt , fwd= $fwd"
- if test -d MITgcm_$tt/verification ; then
+ if test -e $gcmDIR/.git/config -a -d $gcmDIR/verification ; then
  #- cleaning previous testreport run and updating the code:
   if [ $fwd -eq 0 ] ; then
    set -x
   #- cleanup previous test:
-   ( cd MITgcm_$tt/verification ; ./testreport -adm -clean > ../../tr_clean_$tt.log 2>&1 )
+   ( cd $gcmDIR/verification ; ./testreport -adm -clean > ../../tr_clean_$tt.log 2>&1 )
    set +x
   else
    set -x
   #- cleanup previous restart:
-   ( cd MITgcm_$tt/verification ; ../tools/do_tst_2+2 -clean > ../../tr_clean_$tt.log 2>&1 )
+   ( cd $gcmDIR/verification ; ../tools/do_tst_2+2 -clean > ../../tr_clean_$tt.log 2>&1 )
   #- cleanup previous test:
-   ( cd MITgcm_$tt/verification ; ./testreport -clean >> ../../tr_clean_$tt.log 2>&1 )
+   ( cd $gcmDIR/verification ; ./testreport -clean >> ../../tr_clean_$tt.log 2>&1 )
    set +x
   fi
   if [ $gfort -eq 0 ] ; then
-    echo ' remove all Makefile_syntax and do "cvs update -P -d"' >> tr_clean_$tt.log
-    ( cd MITgcm_$tt/verification ; rm -f */build/Makefile_syntax )
-  else
-    echo " run '$cmdCVS update -P -d'"  >> tr_clean_$tt.log
+    echo ' remove all Makefile_syntax' >> tr_clean_$tt.log
+    ( cd $gcmDIR/verification ; rm -f */build/Makefile_syntax )
   fi
-  echo ""
+  echo "" >> tr_clean_$tt.log
 
-  echo "=========================================================================="
+  echo "==========================================================================" \
+       >> tr_clean_$tt.log
+  echo " Update MITgcm code in dir: $gcmDIR using 'git pull':" | tee -a tr_clean_$tt.log
   set -x
   #- update the code:
-  ( cd MITgcm_$tt ; $cmdCVS update -P -d  >> ../tr_clean_$tt.log 2>&1 ; retv=$? )
+  ( cd $gcmDIR ; git checkout master ; git pull ) >> tr_clean_$tt.log 2>&1 ; retv=$?
   set +x
   if test $retv != 0 ; then
-    echo "cvs update in MITgcm_$tt fail (return val=$retv) => skip" | tee -a tr_clean_$tt.log
+    echo "'git pull' in $gcmDIR fail (return val=$retv) => skip" | tee -a tr_clean_$tt.log
     continue
   fi
  else
+  echo "Missing '$gcmDIR/.git/config' or dir '$gcmDIR/verification'" >> tr_clean_$tt.log
+  if test -e $gcmDIR ; then
+    echo -n " removing working copy: $gcmDIR ..."	>> tr_clean_$tt.log
+    rm -rf $gcmDIR
+    echo "  done"					>> tr_clean_$tt.log
+  fi
  #- download new code:
-  echo " run '$cmdCVS co -P -d  MITgcm_$tt MITgcm'"  >> tr_clean_$tt.log
-  echo "=========================================================================="
+  echo "==========================================================================" \
+       >> tr_clean_$tt.log
+  echo "Make a clone of $git_code from repo: $git_repo into: $gcmDIR ..." | tee -a  tr_clean_$tt.log
   set -x
-    $cmdCVS co -P -d  MITgcm_$tt MITgcm >> tr_clean_$tt.log 2>&1 ; retv=$?
+  git clone https://github.com/$git_repo/${git_code}.git $gcmDIR 2> $tmpFil
+  retv=$?
   set +x
-  if test $retv != 0 ; then
-    echo "cvs co of MITgcm_$tt fail (return val=$retv) => skip" | tee -a tr_clean_$tt.log
+  if test $retv = 0 ; then
+    echo '  done' >> tr_clean_$tt.log ; rm -f $tmpFil
+  else
+    echo "'git clone' into $gcmDIR failed (return: $retv) => skip" | tee -a tr_clean_$tt.log
+    cat $tmpFil >> tr_clean_$tt.log ; rm -f $tmpFil
     continue
   fi
  fi
   echo ""
   echo "=========================================================================="
 
- if test -d MITgcm_$tt/verification ; then
+ if test -d $gcmDIR/verification ; then
   if test -e tr_run_$tt.log ; then mv -f tr_run_$tt.log tr_run_$tt.log_bak ; fi
-  cd MITgcm_$tt/verification
+  cd $gcmDIR/verification
 
   date
   # verbose mode:
@@ -133,7 +151,7 @@ case $tt in
   echo '' >> ../../tr_run_$tt.log 2>&1
 
   ./testreport -MPI 3 -adm -of ../tools/build_options/linux_amd64_ifort11 \
-   -devel -q -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+   -devel -q -a $mAddr >> ../../tr_run_$tt.log 2>&1
 
   sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
 ;;
@@ -145,7 +163,7 @@ case $tt in
   echo '' >> ../../tr_run_$tt.log 2>&1
 
   ./testreport -MPI 3 -ur4 -adm -of ../tools/build_options/linux_amd64_ifort11 \
-   -devel -q -match 5 -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+   -devel -q -match 5 -a $mAddr >> ../../tr_run_$tt.log 2>&1
 
   sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
 ;;
@@ -160,13 +178,13 @@ case $tt in
   echo '' >> ../../tr_run_$tt.log 2>&1
 
   ./testreport -MPI 2 -mth -of ../tools/build_options/linux_amd64_ifort11 \
-   -devel -q -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+   -devel -q -a $mAddr >> ../../tr_run_$tt.log 2>&1
 
   sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
 
   #- test restart:
   echo '' >> ../../tr_run_$tt.log 2>&1
-  ../tools/do_tst_2+2 -mpi -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+  ../tools/do_tst_2+2 -mpi -a $mAddr >> ../../tr_run_$tt.log 2>&1
 ;;
 
 'iur4')
@@ -176,19 +194,19 @@ case $tt in
   echo '' >> ../../tr_run_$tt.log 2>&1
 
   ./testreport -MPI 3 -ur4 -of ../tools/build_options/linux_amd64_ifort11 \
-   -devel -q -match 5 -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+   -devel -q -match 5 -a $mAddr >> ../../tr_run_$tt.log 2>&1
 
   sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
 
   #- test restart:
   echo '' >> ../../tr_run_$tt.log 2>&1
-  ../tools/do_tst_2+2 -mpi -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+  ../tools/do_tst_2+2 -mpi -a $mAddr >> ../../tr_run_$tt.log 2>&1
 ;;
 
 'gadm')
 
   ./testreport -MPI 3 -adm -of ../tools/build_options/linux_amd64_gfortran \
-   -devel -ncad -nc -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+   -devel -ncad -nc -a $mAddr >> ../../tr_run_$tt.log 2>&1
 
   sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
 ;;
@@ -196,7 +214,7 @@ case $tt in
 'gads')
 
   ./testreport -adm -of ../tools/build_options/linux_amd64_gfortran \
-   -devel -ncad -nc -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+   -devel -ncad -nc -a $mAddr >> ../../tr_run_$tt.log 2>&1
 
   sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
 ;;
@@ -204,7 +222,7 @@ case $tt in
 'gad4')
 
   ./testreport -adm -ur4 -of ../tools/build_options/linux_amd64_gfortran \
-   -devel -ncad -nc -match 5 -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+   -devel -ncad -nc -match 5 -a $mAddr >> ../../tr_run_$tt.log 2>&1
 
   sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
 ;;
@@ -215,74 +233,74 @@ case $tt in
   export GOMP_STACKSIZE=400m
 
   ./testreport -MPI 2 -mth -of ../tools/build_options/linux_amd64_gfortran \
-   -devel -nc -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+   -devel -nc -a $mAddr >> ../../tr_run_$tt.log 2>&1
 
   sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
 
   #- test restart:
   echo '' >> ../../tr_run_$tt.log 2>&1
-  ../tools/do_tst_2+2 -mpi -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+  ../tools/do_tst_2+2 -mpi -a $mAddr >> ../../tr_run_$tt.log 2>&1
 ;;
 
 'gmpi')
 
   ./testreport -MPI 3 -of ../tools/build_options/linux_amd64_gfortran \
-   -devel -nc -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+   -devel -nc -a $mAddr >> ../../tr_run_$tt.log 2>&1
 
   sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
 
   #- test restart:
   echo '' >> ../../tr_run_$tt.log 2>&1
-  ../tools/do_tst_2+2 -mpi -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+  ../tools/do_tst_2+2 -mpi -a $mAddr >> ../../tr_run_$tt.log 2>&1
 ;;
 
 'gmp4')
 
   ./testreport -MPI 3 -ur4 -of ../tools/build_options/linux_amd64_gfortran \
-   -devel -nc -match 5 -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+   -devel -nc -match 5 -a $mAddr >> ../../tr_run_$tt.log 2>&1
 
   sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
 
   #- test restart:
   echo '' >> ../../tr_run_$tt.log 2>&1
-  ../tools/do_tst_2+2 -mpi -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+  ../tools/do_tst_2+2 -mpi -a $mAddr >> ../../tr_run_$tt.log 2>&1
 ;;
 
 'gfo')
 
   ./testreport -of ../tools/build_options/linux_amd64_gfortran \
-   -devel -nc -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+   -devel -nc -a $mAddr >> ../../tr_run_$tt.log 2>&1
 
   sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
 
   #- test restart:
   echo '' >> ../../tr_run_$tt.log 2>&1
-  ../tools/do_tst_2+2 -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+  ../tools/do_tst_2+2 -a $mAddr >> ../../tr_run_$tt.log 2>&1
 ;;
 
 'gfo4')
 
   ./testreport -ur4 -of ../tools/build_options/linux_amd64_gfortran \
-   -devel -nc -match 5 -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+   -devel -nc -match 5 -a $mAddr >> ../../tr_run_$tt.log 2>&1
 
   sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
 
   #- test restart:
   echo '' >> ../../tr_run_$tt.log 2>&1
-  ../tools/do_tst_2+2 -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+  ../tools/do_tst_2+2 -a $mAddr >> ../../tr_run_$tt.log 2>&1
 ;;
 
 'g77')
 
   ./testreport -of ../tools/build_options/linux_amd64_g77 \
    -skd 'fizhi-cs-32x32x40 fizhi-cs-aqualev20' \
-   -nc -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+   -nc -a $mAddr >> ../../tr_run_$tt.log 2>&1
 
   sed -n "/ email /,/^======== End of testreport / p" ../../tr_run_$tt.log
 
   #- test restart:
   echo '' >> ../../tr_run_$tt.log 2>&1
-  ../tools/do_tst_2+2 -a jm_c@mitgcm.org >> ../../tr_run_$tt.log 2>&1
+  ../tools/do_tst_2+2 -a $mAddr >> ../../tr_run_$tt.log 2>&1
 ;;
 
 *) echo "unrecognized test suffix '$tt' <== skipped" ;;
@@ -292,7 +310,7 @@ esac
   cd ../..
 
  else
-  echo "error: missing dir MITgcm_$tt/verification"
+  echo "error: missing dir $gcmDIR/verification"
  fi
 
 done
